#pragma once

#include "Shared/Message/ExecutionReport.hpp"
#include "Shared/Message/HeartBeat.hpp"
#include "Shared/Message/Logon.hpp"
#include "Shared/Message/Logout.hpp"
#include "Shared/Message/MarketDataIncrementalRefresh.hpp"
#include "Shared/Message/MarketDataRequest.hpp"
#include "Shared/Message/MarketDataSnapshotFullRefresh.hpp"
#include "Shared/Message/NewOrderSingle.hpp"
#include "Shared/Message/OrderCancelReject.hpp"
#include "Shared/Message/OrderCancelReplaceRequest.hpp"
#include "Shared/Message/OrderCancelRequest.hpp"
#include "Shared/Message/OrderStatusRequest.hpp"
#include "Shared/Message/Reject.hpp"
#include "Shared/Message/Serializer.hpp"
#include "Shared/Message/TestRequest.hpp"
#include "Shared/Message/BusinessMessageReject.hpp"