name: Deploy server

on:
  # push:
  #   branches:
  #     - master
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master
  workflow_dispatch:

jobs:
  build-cmake:
    runs-on: ubuntu-latest
    name: CI Server
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/fix-server
          IMAGE=$(echo $IMAGE | tr '[:upper:]' '[:lower:]')
          docker build -f server/Dockerfile -t $IMAGE:latest .
          docker push $IMAGE:latest

  deploy:
    needs: build-cmake
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            IMAGE=ghcr.io/${{ github.repository_owner }}/fix-server
            IMAGE=$(echo $IMAGE | tr '[:upper:]' '[:lower:]')
            docker pull $IMAGE:latest
            docker stop fix-server || true
            docker rm fix-server || true
            docker run -d --name fix-server -p ${{ vars.SERVER_PORT}}:${{ vars.SERVER_PORT_FORWARD }} $IMAGE:latest