name: Deploy & Start Server

on:
  workflow_run:
    workflows: ["Build Server image"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy image
    runs-on: ubuntu-latest

    steps:
      - name: Generate image name
        id: image_generator
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/fix-server
          IMAGE=$(echo $IMAGE | tr '[:upper:]' '[:lower:]')
          echo "image_name=$IMAGE" >> $GITHUB_OUTPUT

      - name: Backup log folder
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e

            SRC="/server-logs"
            DEST_DIR="/backup"

            if [ ! -d "$SRC" ]; then
                sudo mkdir "$SRC"
                exit 0
            fi
            sudo mkdir -p "$DEST_DIR"
            i=1
            while true; do
                DEST_PATH="$DEST_DIR/server-logs_$i"
                if [ ! -e "$DEST_PATH" ]; then
                    break
                fi
                ((i++))
            done
            sudo mv "$SRC" "$DEST_PATH"
            sudo mkdir "$SRC"


      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo ${{ secrets.GITHUB_TOKEN }} | sudo docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
            sudo docker pull ${{ steps.image_generator.outputs.image_name }}:latest
            sudo docker stop fix-server || true
            sudo docker rm fix-server || true
            sudo docker run -d --name fix-server --mount type=bind,src=/server-logs,dst=/app/logs -p ${{ vars.SERVER_PORT}}:${{ vars.SERVER_PORT_FORWARD }} ${{ steps.image_generator.outputs.image_name }}:latest