name: Build Server image

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    name: Build Server image
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/fix-server
          IMAGE=$(echo $IMAGE | tr '[:upper:]' '[:lower:]')
          docker build -f server/Dockerfile -t $IMAGE:latest .
          docker push $IMAGE:latest