name: Shared library Unit Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master
  workflow_dispatch:

jobs:
  build-cmake:
    runs-on: ubuntu-latest
    name: Building cmake & dependency

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++ make

      - name: Configure CMake
        run: |
          mkdir -p build && cd build
          cmake -DCommonBuild=TRUE ..

      - name: Upload build directory
        uses: actions/upload-artifact@v4.6.2
        with:
          name: cmake-build
          path: build
          if-no-files-found: error
          include-hidden-files: true

  build-test:
    needs: build-cmake
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [Network]
    name: Build Unit-Test ${{ matrix.target }}

    steps:
      - name: Download CMake build directory
        uses: actions/download-artifact@v5
        with:
          name: cmake-build
          path: build

      - name: Build target
        run: |
          cd build ${{ matrix.target }}
          cmake --build . -j --target Shared_${{ matrix.target }}_Test

      - name: Run Test ${{ matrix.target }}
        run: ./build/shared/Network/Shared_${{ matrix.target }}_Test